tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.zip
# package1: java-1.8.0-openjdk
package1: openjdk-11-jre
package2: unzip
package3: wget
package4: mariadb-server
package5: python-mysqldb
package6: mysql-server
tomcatfile_src: /opt/apache-tomcat-9.0.70.zip
tomcatfile_dest: /opt
tomcatstudentwar: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
tomcatstudentwardest: /opt/apache-tomcat-9.0.70/webapps
mysqlconnect: https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar
mysqldest: /opt/apache-tomcat-9.0.70/lib
cnfdest: /home/ec2-user/tomcat-server/roles/webserver/template/my.cnf
USERNAME: root
PASSWORD: root123
DB_CONNECTOR: localhost
DATABASE: student