- name: Package installation java
  ansible.builtin.package:
    state: present
    name: "{{package1}}"

- name: Package installation unzip
  ansible.builtin.package:
    state: present
    name: "{{package2}}"

- name: Package installation wget
  ansible.builtin.package:
    state: present
    name: "{{package3}}"

- name: Package installation mysql
  ansible.builtin.package:
    state: present
    name: "{{package4}}"

- name: Package installation mysql
  ansible.builtin.package:
    state: present
    name: "{{package5}}"

- name: Package installation mysql
  ansible.builtin.package:
    state: present
    name: "{{package6}}"

- name: System Update
  shell: yum update

- name: Download Package
  ansible.builtin.get_url:
    url: "{{tomcat_url}}"
    dest: /opt

- name: unzip package
  ansible.builtin.unarchive:
    src: "{{tomcatfile_src}}"
    dest: "{{tomcatfile_dest}}"
    mode: 0775
    remote_src: yes

- name: Download Artifact
  ansible.builtin.get_url:
    url: "{{tomcatstudentwar}}"
    dest: "{{tomcatstudentwardest}}"

- name: Download Artifact
  ansible.builtin.get_url:
    url: "{{mysqlconnect}}"
    dest: "{{mysqldest}}"

- name: copy .my.cnf file with root password credentials
  template: 
    src: my.cnf 
    dest: /root/.my.cnf


- name: Create user in database with name "admin"  
  mysql_user: 
    login_user: root
    login_password: Redhat@123
    name: root
    password: Redhat@123
    host: localhost
    priv: '*.*:ALL'  
    state: present  
    check_implicit_admin: true

- name: Create a new database with name "myFirstDB"  
  mysql_db: 
    name: student
    state: present  
       
- name: add sample data to database  
  template: 
    src: dump.sql 
    dest: /tmp/dump.sql/ 

- name: insert sample data into database  
  mysql_db: 
    name: student
    state: import 
    target: /tmp/dump.sql/dump.sql

- name: service mysql restart
  shell: service restart mariadb

- name: service start
  shell: nohup /opt/apache-tomcat-9.0.70/bin/catalina.sh start